# Generated by Django 6.0.7 on 2026-07-22 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('websocket', 'WebSocket'), ('sms', 'SMS'), ('email', 'Email')], default='websocket', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.report')),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_1dd18d_idx'), models.Index(fields=['report'], name='notificatio_report__6b0664_idx'), models.Index(fields=['channel'], name='notificatio_channel_d2a579_idx'), models.Index(fields=['sent_at'], name='notificatio_sent_at_eceac5_idx')],
            },
        ),
    ]
