# Generated by Django 6.0.7 on 2026-08-18 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_message_attachment_alter_message_content'),
        ('reports', '0012_emergency_dispatch_redesign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('failed', 'Failed')], default='created', max_length=10),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notificatio_status_fce6f5_idx'),
        ),
    ]
