# Generated by Django 6.0.7 on 2026-07-23 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_client_timestamp_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='sync_origin',
            field=models.CharField(choices=[('live', 'Live'), ('sync', 'Offline Sync')], default='live', max_length=10),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['sync_origin'], name='audit_logs_sync_or_7decd3_idx'),
        ),
    ]
