# Generated by Django 6.0.7 on 2026-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_sync_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('status_update', 'Status Update'), ('assign', 'Assign'), ('evidence_upload', 'Evidence Upload'), ('deanonymize', 'Deanonymize'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('auto_route', 'Auto Route'), ('routing_suggestion', 'Routing Suggestion'), ('department_transfer', 'Department Transfer'), ('escalate', 'Escalate')], max_length=20),
        ),
    ]
