# Generated by Django 6.0.7 on 2026-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('status_update', 'Status Update'), ('assign', 'Assign'), ('evidence_upload', 'Evidence Upload'), ('deanonymize', 'Deanonymize'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('auto_route', 'Auto Route'), ('routing_suggestion', 'Routing Suggestion'), ('department_transfer', 'Department Transfer'), ('escalate', 'Escalate'), ('request_assistance', 'Request Assistance'), ('acknowledge_assistance', 'Acknowledge Assistance'), ('feedback_requested', 'Feedback Requested'), ('submit_feedback', 'Submit Feedback'), ('view_feedback', 'View Feedback')], max_length=30),
        ),
    ]
