# Generated by Django 6.0.7 on 2026-08-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_emergency_dispatch_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
