# Generated by Django 6.0.7 on 2026-08-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_add_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
