# Generated by Django 6.0.7 on 2026-08-29 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_user_agent_nullable'),
        ('reports', '0013_backfill_emergency_dispatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('status_update', 'Status Update'), ('assign', 'Assign'), ('evidence_upload', 'Evidence Upload'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('permanent_delete', 'Permanently Deleted'), ('auto_route', 'Auto Route'), ('routing_suggestion', 'Routing Suggestion'), ('feedback_requested', 'Feedback Requested'), ('submit_feedback', 'Submit Feedback'), ('view_feedback', 'View Feedback'), ('responder_created', 'Responder Created'), ('head_created', 'Head Created'), ('account_created', 'Account Created'), ('role_changed', 'Role Changed'), ('account_activated', 'Account Activated'), ('account_deactivated', 'Account Deactivated'), ('emergency_acknowledged', 'Emergency Acknowledged'), ('emergency_responding', 'Emergency Responding'), ('emergency_arrived', 'Emergency Arrived'), ('emergency_escalated', 'Emergency Escalated'), ('emergency_cancelled', 'Emergency Cancelled'), ('emergency_false_alarm', 'Emergency Marked False Alarm')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='reports.report'),
        ),
    ]
