# Generated by Django 6.0.7 on 2026-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('security', 'Security Officer'), ('ict_admin', 'ICT Admin'), ('management', 'Management / Escrow'), ('system_admin', 'System Admin')], default='student', max_length=20),
        ),
    ]
