# Generated by Django 6.0.7 on 2026-07-22 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('medical', 'Medical'), ('fire', 'Fire'), ('harassment_gbv', 'Harassment / GBV'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('panic', 'Panic'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'security'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reports.report')),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='ReportIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_reporter_ref', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='reports.report')),
            ],
            options={
                'db_table': 'report_identities',
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_status_e83c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category'], name='reports_categor_81258c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['urgency'], name='reports_urgency_dfcd76_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_created_c5f642_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_to'], name='reports_assigne_201c76_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['idempotency_key'], name='reports_idempot_b297b2_idx'),
        ),
    ]
