# Generated by Django 6.0.7 on 2026-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_custom_department_report_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('medical', 'Medical'), ('fire', 'Fire'), ('harassment_gbv', 'Harassment / GBV'), ('academic', 'Academic'), ('other', 'Other')], max_length=20),
        ),
    ]
