# Generated by Django 6.0.7 on 2026-08-04 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportidentity_reporter_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportidentity',
            new_name='report_iden_reporte_cfb156_idx',
            old_name='report_iden_reporte_e4a1b0_idx',
        ),
        migrations.AlterField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('theft', 'Theft'), ('assault', 'Assault'), ('medical', 'Medical'), ('fire', 'Fire'), ('harassment_gbv', 'Harassment / GBV'), ('academic', 'Academic'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
