# Generated by Django 6.0.7 on 2026-08-05 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_rename_report_iden_reporte_e4a1b0_idx_report_iden_reporte_cfb156_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('departments', models.ManyToManyField(related_name='assistance_requests', to='reports.department')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='reports.report')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistance_requests',
            },
        ),
        migrations.CreateModel(
            name='ReportFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reports.report')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_feedback',
            },
        ),
        migrations.CreateModel(
            name='AssistanceAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.department')),
                ('assistance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='reports.assistancerequest')),
            ],
            options={
                'db_table': 'assistance_acknowledgements',
                'unique_together': {('assistance_request', 'department')},
            },
        ),
    ]
