# Generated by Django 6.0.7 on 2026-08-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_backfill_report_reporter'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportidentity',
            name='report_iden_reporte_cfb156_idx',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_anonymous',
        ),
        migrations.DeleteModel(
            name='ReportIdentity',
        ),
    ]
