# Generated by Django 6.0.7 on 2026-08-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_drop_anonymous_reporting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistancerequest',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='assistancerequest',
            name='report',
        ),
        migrations.RemoveField(
            model_name='assistancerequest',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='AssistanceAcknowledgement',
        ),
        migrations.DeleteModel(
            name='AssistanceRequest',
        ),
    ]
