# Generated by Django 6.0.7 on 2026-08-18 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_drop_assistance_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('false_alarm', 'False Alarm')], default='new', max_length=15),
        ),
        migrations.CreateModel(
            name='EmergencyDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_type', models.CharField(choices=[('security', 'Security / Threat'), ('medical', 'Medical Emergency'), ('fire', 'Fire'), ('accident', 'Accident'), ('other', 'Other')], default='other', max_length=10)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('responding_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ack_deadline', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolution_deadline', models.DateTimeField(blank=True, null=True)),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_emergencies', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_emergencies', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_dispatch', to='reports.report')),
            ],
            options={
                'db_table': 'emergency_dispatches',
                'indexes': [models.Index(fields=['emergency_type'], name='emergency_d_emergen_aaf92e_idx'), models.Index(fields=['ack_deadline'], name='emergency_d_ack_dea_ccf593_idx'), models.Index(fields=['response_deadline'], name='emergency_d_respons_a0927a_idx'), models.Index(fields=['resolution_deadline'], name='emergency_d_resolut_575288_idx')],
            },
        ),
    ]
