# Generated by Django 6.0.7 on 2026-08-18 08:26

from django.db import migrations


def backfill_emergency_dispatch(apps, schema_editor):
    """
    Every pre-existing urgency='panic' Report gets an EmergencyDispatch row
    (all timestamps null, emergency_type='other') so downstream code can
    assume the row always exists for any panic report rather than
    special-casing its absence everywhere. Normal reports never get one.
    """
    Report = apps.get_model('reports', 'Report')
    EmergencyDispatch = apps.get_model('reports', 'EmergencyDispatch')
    panic_reports = Report.objects.filter(urgency='panic').exclude(emergency_dispatch__isnull=False)
    EmergencyDispatch.objects.bulk_create(
        [EmergencyDispatch(report=report, emergency_type='other') for report in panic_reports]
    )


def reverse_noop(apps, schema_editor):
    # Reversing would delete rows an operator may have since started
    # populating (acknowledged_at, etc.) — deliberately a no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_emergency_dispatch_redesign'),
    ]

    operations = [
        migrations.RunPython(backfill_emergency_dispatch, reverse_noop),
    ]
