# Generated by Django 6.0.7 on 2026-09-09 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_backfill_emergency_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencydispatch',
            name='emergency_type_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencydispatch',
            name='emergency_type',
            field=models.CharField(default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='EmergencyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_description_and_routing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_categories', to='reports.department')),
            ],
            options={
                'db_table': 'emergency_categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='emergency_c_slug_d45d34_idx'), models.Index(fields=['is_active'], name='emergency_c_is_acti_9f9aa3_idx'), models.Index(fields=['sort_order'], name='emergency_c_sort_or_071577_idx')],
            },
        ),
    ]
